site_name: Genome Analysis
site_url: https://github.com/WonyoungCho/plink
site_description: Tutorial review of plink
repo_url: https://github.com/WonyoungCho/plink/
site_author: Wonyoung Cho

extra_javascript: [docs.js]

pages:
    - Home: 'index.md'
    - Plink:
        - 'Introduction' : 'plink_int.md'
        - 'File format' : 'plink_fmt.md'
        - 'Data manipulation' : 'plink_mani.md'
        - 'BCFtools' : 'bcftools_mani.md'
        - 'VCF-validator' : 'vcf_validator.md'
        - 'Example' : 'plink_ex.md'
    - Epistasis: 'epistasis.md'
    - Chapter11: 'chapter11.md'
    - GWAS QC: 'GWAS.md'
    - GWAS script: 'GWAS_bash.md'
    - Analysis script: 'analysis_bash.md'
    - Plink2:
        - 'Example' : 'plink2_ex.md'
    - Terminology: 'terminology.md'
    - Python:
        - 'Combination' : 'python_combo.md'
        - 'Module' : 'python_module.md'
        - 'Plot' : 'python_plot.md'
        - 'Useful' : 'python_useful.md'
    - HapMap: 'hapMap1KG_ch7_8.md'
    - Reference: 'data_ref.md'
    - Samtools:
        - 'Installation' : 'samtools_ins.md'
        - 'Introduction' : 'samtools_int.md'
        - 'Option' : 'samtools_opt.md'
    - BEDOPS: 'bedops_int.md'
    - Gviz: 'Gviz_int.md'
    - Specification: 'com_spec.md'
theme: readthedocs
